<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ijs</string>
		<string>ijt</string>
		<string>ijx</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>J</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|\s|\W)_?[0-9][_0-9\.a-zA-Z]*</string>
			<key>name</key>
			<string>constant.numeric.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|\s)(NB\..*$)</string>
			<key>name</key>
			<string>comment.line.j</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=0 : 0$)</string>
			<key>end</key>
			<string>(?=^\)|\s\))</string>
			<key>name</key>
			<string>string.block.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\'.*?\'</string>
			<key>name</key>
			<string>string.quoted.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[-!#$%\*+,;&lt;=&gt;\?\[\]^{|]</string>
			<key>name</key>
			<string>keyword.verb.j</string>
		</dict>
		<dict>
			<key>match</key>
			<string>assert\.|break\.|case\.|catch\.|catchd\.|catcht\.|continue\.|do\.|else\.|elseif\.|end\.|fcase\.|if\.|return\.|select\.|throw\.|try\.|while\.|whilst\.</string>
			<key>name</key>
			<string>keyword.control.j</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Needs better scope than function</string>
			<key>match</key>
			<string>(?&lt;=^|\s)[a-zA-Z][a-zA-Z_0-9]*(?=\s*\=\:)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ijs</string>
	<key>uuid</key>
	<string>2AD4807E-CE3B-4068-8CC3-D6AE02689BE1</string>
</dict>
</plist>
